# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1cbf5eba5c749d53cd6f7dc52f5424ca6f5c772c6b9cb9e693eba4ae9a20198da7be5ed2451f823c943d4a4d593340c7d59498a202dd99660556c4e73d12534

test:
  secret_key_base: 9f89f9614c5cb7697710b99e98acf4bdbbcb3f8befc9b1c2a5dadfcaef76fc4a8d1a4322fd3e12a53213247fbec2bcd6e53a0d0ae162aecefe0bf7d56c322488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
